site_name: MotorControlHMI Docs
theme:
  name: material

nav:
  - Home: index.md
  - HMI Pages:
      - Motor Controls: motor_control.md
      - Measured Values: measured_values.md
      - Systems Info: systems_info.md
  - Project Compile: how_to_use.md
