site_name: MotorControlHMI Docs
theme:
  name: material

plugins:
  - search

nav:
  - Home: index.md
  - HMI Pages:
      - Motor Controls: motor_control.md
      # - Measured Values: docs/measured_values.md
