name: Build EmbeddedWizard Project

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup ARM GCC
        uses: ryanclaassen/setup-arm-gcc@v1
        with:
          version: '12.2-2022.11'

      - name: Install make
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: make

      - name: Build project
        run: .\StartGccBuildEnvironment.bat
